default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_rb_development

test:
  <<: *default
  database: todo_list_rb_test

production:
  <<: *default
  host: <%= ENV["DOCKER_POSTGRES_HOST"] %>
  database: <%= ENV["DOCKER_POSTGRES_DATABASE"] %>
  username: <%= ENV["DOCKER_POSTGRES_USERNAME"] %>
  password: <%= ENV["DOCKER_POSTGRES_PASSWORD"] %>
  connect_timeout: 2
  checkout_timeout: 5
  variables:
    statement_timeout: 5000
