default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  database: todo_list_rb_<%= Rails.env %>
  host: localhost
  username: <%= ENV['LOCAL_POSTGRES_USER'] %>
  password: <%= ENV['LOCAL_POSTGRES_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  sslmode: require
  connect_timeout: 2
  checkout_timeout: 5
  variables:
    statement_timeout: 5000
