default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_rb_development

test:
  <<: *default
  database: todo_list_rb_test

production:
  <<: *default
  database: todo_list_rb_production
  username: todo_list_rb
  password: <%= ENV["TODO_LIST_RB_DATABASE_PASSWORD"] %>
