# frozen_string_literal: true

# == Schema Information
#
# Table name: category_task_lists
#
#  id           :bigint           not null, primary key
#  category_id  :bigint           not null
#  task_list_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class CategoryTaskList < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :category
  belongs_to :task_list

  # @validations ..............................................................
  validates :category_id, uniqueness: { scope: :task_list_id }

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end
